qube_version: '2.5.1 # <<QUBE_NO_BUMP>>'
full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: Garage
project_short_description: Garage. A qube based .
version: 0.1.0-SNAPSHOT
domain: lib
language: groovy
project_slug: Garage
project_slug_no_hyphen: Garage
template_version: '1.0.0 # <<QUBE_NO_BUMP>>'
template_handle: lib-groovy
github_username: sven1103
creator_github_username: sven1103
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
